name: Utgje

on:
  push:
    branches:
      - "hovud"
  workflow_dispatch:

jobs:
  utgje:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip install -r pylode_krav.txt
          python pylode/vevskrivar.py
          if git diff --exit-code; then
              git config user.name 'github-actions[bot]'
              git config user.email 'github-actions[bot]@users.noreply.github.com'
              git add .
              git commit -m "automatisk utgjevelse"
              git push 
          exit 0         
          